= Power Input/Output

The SC-OBC Module V1 operates primarily on a single 5 V power supply
provided by the carrier board. However, by supplying power to the IO
banks from the carrier board, signals of any voltage level can be
connected to the IO bank signals. For this purpose, the SC-OBC Module
V1 includes dedicated pathways for the IO bank power input.

The SC-OBC Module V1 generates power internally from the 5 V input
from the carrier board and outputs it as a power supply line. This
output is intended as a power supply for circuits on the carrier
board. Furthermore, depending on the carrier board design, this output
power can also be connected to the module's VCCO input pin to serve as
the power supply for the module's IO banks.

The power lines available via the SC-OBC Module V1's board-to-board
connector are as follows:

.Power Input/Output List
[cols=",,,",options="header"]
|===
|VIN_5V0             |Power  Input          |5                     |Main power input from the carrier board
|VCC_BATT_IN         |Power  Input          |1.2 - 1.5             |Power input for the real-time clock (RTC)
|VDD_3V3_OUT         |Power  Output         |3.3                   |3.3V power output for user circuit
|VDD_1V8_OUT         |Power  Output         |1.8                   |1.8V power output for user circuit
|VDD_1V2_OUT         |Power  Output         |1.2                   |1.2V power output for user circuit
|VCCO_500_501_OUT    |Power  Output         |1.8                   |Versal Bank 500 /501 1.8V power output
|VCCO_503_OUT        |Power  Output         |1.8                   |Versal Bank 503 (JTAG) 1.8V power output
|M2GL_VDDI4_OUT      |Power  Output         |1.8                   |IGLOO2 Bank 4 (JTAG) 1.8V power output
|VCCO_502_IN         |IO Bank Power Input   |1.8/2.5/3.3           |Power input for Versal LPD MIO Bank 502
|VCCO_703_IN         |IO Bank Power Input   |1.0/1.2/1.35/1.5      |Power input for Versal PL XPIO Bank 703
|VCCO_302_IN         |IO Bank Power Input   |1.8/2.5/3.3           |Power input for Versal PL HDIO Bank 302
|M2GL_VDDI5_IN       |IO Bank Power Input   |1.2/1.5/1.8/2.5/3.3   |Power input for IGLOO2 Bank 5
|M2GL_VDDI8_IN       |IO Bank Power Input   |1.2/1.5/1.8/2.5/3.3   |Power input for IGLOO2 Bank 8
|===

When VIN_5V0 is applied, the output power generated by the SC-OBC
Module V1's DC-DC converter supplies VDD_3V3_OUT, VDD_1V8_OUT and
VDD_1V2_OUT, making them immediately available. Users can utilize
these power rails to supply circuits on the carrier board. Each output
includes overcurrent protection, with VDD_3V3_OUT rated for up to 1 A
and VDD_1V8_OUT and VDD_1V2_OUT rated for up to 300 mA.

.Power Up Timing
image::power-up-timing.svg[Power Up Timing]

The table above defines two types of Power Enable signals for the
three IO bank power inputs, enabling arbitrary power-saving
control. Both signals are output from the SC-OBC Module V1 and wired
to the carrier board. When the _PWREN line is asserted, the carrier
board should supply power to the corresponding power input pin. When
deasserted, power supply may be stopped to reduce standby current and
overall power consumption. Alternatively, a configuration in which
power is supplied continuously regardless of the Power Enable signal's
state is also acceptable.

Specifically, the following applies:

* VCCO_302_703_PWREN controls both VCCO_302_IN and VCCO_703_IN
* VCCO_502_PWREN controls VCCO_502_IN

.Power Control by PWREN Signals
image::power-control-by-pwren-signals.svg[Power Control by PWREN Signals]

.Power Input/Output List
[cols=","]
|===
|IO Bank Power Input |Power Enable Signal

|VCCO_502_IN
|VCCO_502_PWREN

|VCCO_302_IN
.2+|VCCO_302_703_PWREN

|VCCO_703_IN

|M2GL_VDDI5_IN
|N/A

|M2GL_VDDI8_IN
|N/A

|===

== Example LPD MIO Connection Circuit on the Carrier Board

The following shows an example configuration on the carrier board side
for connecting a device requiring a 1.8 V power supply to LPD MIO
Bank 502.

.Carrier Board Design Example with LPD MIO Bank 502
image::carrier-board-design-example-lpdmio-bank502.svg[Carrier Board Design Example with LPD MIO Bank 502]

When using the LPD MIO Bank 502, power must be supplied to pin
VCCO_502_IN. Since VCCO_502_IN has a corresponding Power Enable
signal, VCCO_502_PWREN, this signal can be used as the enable input to
generate VCCO_502_IN. In this example, VDD_1V8_OUT is used as the
power source to supply 1.8 V to devices on the carrier board. A power
switch controlled by VCCO_502_PWREN controls the supply to
VCCO_502_IN.

== Example PMC MIO Connection Circuit on the Carrier Board

The following shows an example configuration on the carrier board for
connecting a device requiring both 1.8 V and 3.3 V power supplies,
such as an eMMC, to PMC MIO Bank 500.

.Carrier Board Design Example with PMC MIO Bank 500
image::carrier-board-design-example-pmcmio-bank500.svg[Carrier Board Design Example with PMC MIO Bank 500]


== Example PL HDIO Connection Circuit on Carrier Board

The following shows an example configuration on the carrier board side
for connecting a device requiring a 3.3 V power supply to PL HDIO
Bank 302.

.Carrier Board Design Example with PL HDIO Bank 302
image::carrier-board-design-example-hdio-bank302.svg[Carrier Board Design Example with PL HDIO Bank 302]
