= Product Overview

== Specifications

.Main Processor
[cols="1,1"]
|===
|Feature|Description

|Device
|AMD Versal AI Edge Series VE2302

|Application Processor
|Up to 1.30 GHz Dual core Arm Cortex-A72 +
48 KB/32 KB L1 Cache w/ parity & ECC +
1 MB L2 Cache w/ ECC

|Real-time Processor
|Up to 600 MHz Dual core Arm Cortex-R5F +
32 KB/32 KB L1 Cache +
256 KB TCM w/ECC

|AI Engine
|AI Engine-ML Tiles: 34 +
AIE/AIE-ML Data Memory: 17 Mb +
AIE-ML Shared Memory: 68 Mb

|Programmable Logic
|System Logic: 328,720 +
LUTs: 150,272 +
DSP Engines: 464 +
NoC Master / NoC Slave Ports: 5 +
Distributed RAM: 4.6 Mb

|Memory
|Total Block RAM: 5.4 Mb +
UltraRAM: 43,6 Mb +
Accelerator RAM: 32 Mb +
DDR Memory Controllers: 1 (Bus Width: 64)

|===


.Safety Processor
[cols="1,1"]
|===
|Feature|Description

|Device
|Microchip IGLOO2 (M2GL090)

|===

.On Board Memory
[cols="1,1"]
|===
|Feature|Description

|DDR Memory
|DDR4 memory 4 GB w/ ECC

|Boot Memory
|NOR Flash memory 64 MB x 2

|Storage
|eMMC 64 GB

|High Reliability Memory
|FRAM 1 MB x 2

|===

.Operating System
[cols="1,1"]
|===
|Feature|Description

|APU
|Linux

|RPU
|Zephyr RTOS

|===

.Board to Board Interface (User IO)
[cols="1,1"]
|===
|Feature|Description

|Versal PMC MIO 0
|14 signals +
Platform Management MIO[25:12] +
VDDIO: 1.8 V

|Versal PMC MIO 1
|13 signals +
Platform Management MIO[49:37] +
VDDIO: 1.8 V

|Versal LPD MIO
|26 signals +
Low Power Domain MIO[25:0] +
VDDIO: 1.8/2.5/3.3 V

|Versal PL XPIO
|54 signals (Versal Bank 703) +
VDDIO: 1.0/1.2/1.35/1.5 V

|Versal PL HDIO
|22 signals +
VDDIO: 1.8/2.5/3.3 V

|Versal GTYP0
|20 signals +
Clock: 2 pair +
TX: 4 pair +
RX: 4 pair

|Versal GTYP1
|20 signals +
Clock: 2 pair +
TX: 4 pair +
RX: 4 pair

|IGLOO2 MSIO 0
|32 signals (IGLOO2 Bank 5) +
VDDIO: 1.2/1.5/1.8/2.5/3.3 V

|IGLOO2 MSIO 1
|16 signals (IGLOO2 Bank 8) +
VDDIO: 1.2/1.5/1.8/2.5/3.3 V

|===

.Board Health Function
[cols="1,1"]
|===
|Feature|Description

|On-Board Sensor
|Temperature Sensor +
Current/Voltage Monitor

|Power Management
|Over-current Detection +
Brownout Protection

|===

.Environmental Characteristics
[cols="1,1"]
|===
|Feature|Description

|Power Supply
|DC 5.0 V

|Operating Temperature
|-40 to 80 °C

|Dimentions
|100 mm x 150 mm

|===

== Block Diagram

The SC-OBC Module V1 configures the OBC using two boards (the OBC
Module and the Carrier Board) to maintain high flexibility through the
use of FPGAs.

The OBC Module implements highly reusable functions, including DDR4
memory, Boot Storage and Main Storage, which remain unaffected even if
the interface configuration of the system adopting it
changes. Conversely, the Carrier Board implements functions influenced
by the system configuration, such as the Transceiver IC and Protocol
Converter IC required to meet the electrical specifications of the
interfaces.

Users employing the SC-OBC Module V1 can easily build systems
compatible with new satellites by redesigning the Carrier Board, even
if the satellite system changes. This allows significant reuse of
software assets across systems adopting the same OBC Module, even when
the satellite system changes.

The OBC Module and Carrier Board connect via a 400-pin board-to-board
connector.

image::block_diagram.svg[Block Diagram]
