name: Build Test

on:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: v1-product

      - name: Checkout sc-docs
        uses: actions/checkout@v6
        with:
          repository: spacecubics/sc-docs
          path: sc-docs

      - name: Checkout V1 Software Manual
        uses: actions/checkout@v6
        with:
          repository: spacecubics/scobc-v1-software-manual
          path: v1-software

      - name: Checkout V1 FPGA Manual
        uses: actions/checkout@v6
        with:
          repository: spacecubics/scobc-v1-fpga-developers-guide
          path: v1-fpga

      - name: Install Tools
        run: |
          sudo apt-get update
          sudo apt-get install tree

      - name: Test dirs
        run: |
          pwd
          tree

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install Antora
        run: npm install antora

      - name: Print Node and Antora version
        run: |
          npx node --version
          npx antora --version

      - name: Build it
        working-directory: sc-docs
        run: |
          npx antora generate --log-failure-level warn antora-playbook-v1-local.yml
